// // import Navbar from '@/components/Sidebar';
// import "@/app/styles/globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Toaster } from "@/components/ui/toaster";
// import Provider from "@/components/Provider";
// // import Sidebar from '@/components/Sidebar';

// const inter = Inter({ subsets: ["latin"] });

// import Header from "@/components/Header";
// import Sidenav from "@/components/navbar/Sidenav";

// export const metadata: Metadata = {
//   title: "Trip Notes",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Provider>
//           {/* <Header /> */}
//           <div className="flex">
//             <Sidenav />
//             <div className="w-full overflow-x-auto">
//               <div className="sm:h-[calc(99vh-60px)] overflow-auto ">
//                 <div className="w-full flex justify-center mx-auto   overflow-auto h-[calc(100vh - 120px)] overflow-y-auto relative">
//                   <div className="w-full md:max-w-6xl">{children}</div>
//                 </div>
//               </div>
//             </div>
//           </div>

//           {/* <main className=''>
//         </main> */}
//           {/* <Toaster /> */}
//         </Provider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ContextProvider from '@/components/navbar/ContextProvider';

import '../app/styles/globals.css';

import SideNav from '@/components/navbar/Sidenav';

import Header from './header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TripNotes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Header />
          <div className="flex">
            <SideNav />
            <div className="w-full overflow-x-auto">
              <div className="sm:h-[calc(99vh-60px)] overflow-auto ">
                <div className="w-full flex justify-center mx-auto   overflow-auto h-[calc(100vh - 120px)] overflow-y-auto relative">
                  <div className="w-full md:max-w-6xl">{children}</div>
                </div>
              </div>
            </div>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}